T13314
endlessm/basin pull request #1
Opened 2017-03-20 18:09 UTC by tchx84

https://phabricator.endlessm.com/T13314

2017-03-29 19:07 UTC, ptomato requested changes
Some small changes. I will test this together with the other pull request.

2017-03-29 19:07 UTC, ptomato commented on Makefile.am
> +CLEANFILES += basin
This is duplicated on line 50.

2017-03-29 19:07 UTC, ptomato commented on autogen.sh
> +FILE_MUST_EXIST=src/main.js
I prefer to use `configure.ac` for this purpose, since source files are often renamed.

2017-03-29 19:07 UTC, ptomato commented on Makefile.am
> +	-e 's|@bindir[@]|$(bindir)|g' \
Only `@pkgdatadir@` is present in `basin.in`, so you don't need to substitute `@bindir@` and `@datadir@`.

2017-03-29 19:07 UTC, ptomato commented on configure.ac
> +AM_INIT_AUTOMAKE([-Wall -Wno-portability foreign 1.11 tar-ustar])
Use `dist-xz dist-no-gzip` as well, for modern packages

2017-03-29 19:07 UTC, ptomato commented on configure.ac
> +AC_PROG_AWK
I don't think awk is used anywhere

2017-03-29 19:07 UTC, ptomato commented on configure.ac
> +EOS_CHECK_GJS_GIR([Gio], [2.0])
Use [`AX_CHECK_GIRS_GJS`](https://www.gnu.org/software/autoconf-archive/ax_check_girs_gjs.html) instead.

2017-03-29 19:07 UTC, ptomato commented on m4/eos-gir.m4
> +dnl Copyright 2017 Endless Mobile, Inc.
Delete this, use the upstream version instead.

2017-03-29 19:07 UTC, ptomato commented on src/index.js
> +    }
nitpick: Use trailing commas everywhere

2017-03-29 19:07 UTC, ptomato commented on src/index.js
> +        this._db = new Xapian.WritableDatabase({ path: db_dir,
nitpick: Use our usual indentation style here

2017-03-29 19:07 UTC, ptomato commented on src/index.js
> +        this._db.set_metadata('XbStopwords', JSON.stringify(stopwords));
There are no stopwords yet, maybe better to leave this out?

2017-03-29 19:07 UTC, ptomato commented on src/packer.js
> +        this._json['articles'].forEach((entry) => {
optional: `this._json['articles'].forEach(this._add_article, this);` is more concise but arguably less readable

2017-03-30 15:33 UTC, tchx84 commented on src/index.js
> +        this._db.set_metadata('XbStopwords', JSON.stringify(stopwords));
Our back-end seems to expect that field to be present, so I rather leave it there, even if its empty for now.

2017-03-30 17:24 UTC, ptomato commented on src/index.js
> +        this._db.set_metadata('XbStopwords', JSON.stringify(stopwords));
That would be good to explain in a comment.

2017-03-30 17:51 UTC, tchx84 commented on src/index.js
> +        this._db.set_metadata('XbStopwords', JSON.stringify(stopwords));
Sure, let me push that change.

2017-03-31 00:49 UTC, ptomato requested changes
Some more small changes, the most important of which is to use a `Map` for the dictionary.

2017-03-31 00:49 UTC, ptomato commented on autogen.sh
> +rm -f po/Makevars.template
You don't need this line if not using Gettext.

2017-03-31 00:49 UTC, ptomato commented on src/index.js
> +        // XXX stopwords field is required so leave it empty for now
No `XXX` needed, this is not really a FIXME situation

2017-03-31 00:49 UTC, ptomato commented on src/links.js
> +        this._links = {};
Better to use a `Map` here.

2017-03-31 00:49 UTC, ptomato commented on src/main.js
> +    let json_path = argv[0];
`let [json_path, shard_path] = argv`?

2017-04-01 00:43 UTC, ptomato approved these changes
**CR pass**

2017-04-01 00:43 UTC, merged