packer: Deal gracefully with missing manifest keys
endlessm/basin pull request #34
Opened 2018-05-01 18:12 UTC by ptomato

If writing a manifest by hand, it's inconvenient to have to list a bunch
of keys with empty array values. Instead, make these keys optional.

https://phabricator.endlessm.com/T16018

2018-05-04 17:10 UTC, tchx84 requested changes
Left two comments

2018-05-04 17:10 UTC, tchx84 commented on src/packer.js
> +
Not sure this is necessary, I mean, the tools need to make sure to add the "right" tags, and they do:

* https://github.com/endlessm/basin/blob/master/tools/incubator.js#L180
* https://github.com/endlessm/basin/blob/master/tools/processor.js#L99

2018-05-04 17:10 UTC, tchx84 commented on tools/incubator.js
> +   let incubator = new Incubator(hatch_dir, manifest_path, create_sets);
We could move this to the hatch_sets.json file... adding a new property, like `ignore-sets: true`?

2018-05-17 16:23 UTC, ptomato commented on src/packer.js
> +
It's convenient though, as otherwise in a manually crafted `sets.json` you have to add `"tags": ["EknSetObject"]` ten times, whereas it could be implicitly understood by virtue of being found under a key called `"sets"` :smile:

2018-05-17 16:32 UTC, tchx84 commented on src/packer.js
> +
The problem is I actually want to move away from hard-coding e-k-l-specific object models into the core bits of basin (to make it more flexible, for other use cases like recipes). Doing this goes in the opposite direction, that is why I suggested that maybe we need a tool for crating permanent shards for e-k-l sets (would include this, and maybe even downloading of the thumbnails).

2018-05-22 13:25 UTC, tchx84 requested changes

2018-05-22 13:25 UTC, tchx84 commented on tools/incubator.js
> +        if (!('tags' in this._sets))
You need to ensure that `this._sets` is not `null`, in case the file doesn't exist.

2018-05-22 13:25 UTC, tchx84 commented on src/packer.js
> +
Following up with this, I definitely need to re-design the basin manifest format itself to make the packer less e-k-l-centrist, so ideally we would not even have a "sets" section anymore, just objects.

If we add this hard-coded ekn specific tag here, I will need you to remove it from the tools so we don't end up adding duplicated tags, like:

```
{
  "childTags": [
    "Sports"
  ],
  "tags": [
    "EknSetObject",
    "EknSetObject"
  ],
  "title": "Sports",
  "featured": false,
  "@id": "ekn:///f99aecef3d12e02dcbb6260bbdd35189c89e6e73",
  "@type": "ekn://_vocab/SetObject"
}
```
And that will indeed move the code farther from what I am envisioning. So, to me it clear that we shouldn't do this, and that we should a) add the tag in the example you wrote for the docs, or b) add another tool that handles this. But a) sounds perfectly reasonable to me.

2018-05-22 13:55 UTC, tchx84 commented on src/packer.js
> +
A simpler middle ground could be to just check if its already included, but acknowledging that will this "feature" of adding the tag automatically in the packer will go away.

2018-05-22 19:47 UTC, tchx84 requested changes
```
(gjs:7): Gjs-WARNING **: 15:44:43.763: JS ERROR: TypeError: this._sets is null
Incubator<._import_set@/usr/share/basin/tools/incubator.js:179:1
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Incubator<._import_hatch/<@/usr/share/basin/tools/incubator.js:235:32
Incubator<._import_hatch@/usr/share/basin/tools/incubator.js:234:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Incubator<.run@/usr/share/basin/tools/incubator.js:274:24
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
main@/usr/share/basin/tools/incubator.js:293:4
@<command line>:3:1

Script <command line> threw an exception
```

There is still one missing check, it seems.

2018-05-23 19:20 UTC, tchx84 approved these changes

2018-05-23 19:20 UTC, merged